#!/bin/bash

set -e

##############
# root check #
##############

if [[ -z "$DESTDIR" ]] && [[ "$EUID" != 0 ]]; then
	printf '%s\n' 'e: must be run as root'
	exit 1
fi

#############
# variables #
#############

# not strictly necessary, but for reference
packages_to_download=()
package_names_to_download=()
local_packages_to_install=()

packages_to_install=()
package_names_to_install=()

skipped_package_names=()

#############
# functions #
#############

run_hooks() {
	# function to run package hooks

	printf '%s\n' 'i: running package hooks...'

	package_index=0

	# iterate through packages installed
	for package_name in "${package_names_to_install[@]}"; do
		# skip if package was to be skipped
		skip_package=
		for _package_name in "${skipped_package_names[@]}"; do
			if [[ "$package_name" == "${_package_name}" ]]; then
				skip_package='true'
			fi
		done
		if [[ "$skip_package" == 'true' ]]; then
			continue
		fi

		# status message
		printf '%s\n' "($(( package_index + 1 ))/${#packages_to_install[@]}) running hooks for ${package_name}..."

		# check if hook exists
		if [[ -f "${DESTDIR}/usr/lib/based/pkgs/${package_name}/hooks/install" ]]; then
			# check if installing to / or a different rootfs
			if [[ -z "${DESTDIR}" ]]; then
				"/usr/lib/based/pkgs/${package_name}/hooks/install" || true
			else
				if [[ "$EUID" == 0 ]]; then
					chroot "${DESTDIR}" "/usr/lib/based/pkgs/${package_name}/hooks/install" || true
				else
					unshare -UrR "${DESTDIR}" -- "/usr/lib/based/pkgs/${package_name}/hooks/install" || true
				fi
			fi
		fi

		(( package_index++ )) || true
	done

	printf '%s\n\n' 'i: ran all package hooks.'
}

install_local_package() {
	# function to install a local package

	package="$1" # package location
	package_name="$2" # package name

	# status message
	printf '%s\n' "($(( package_index + 1 ))/${#packages_to_install[@]}) installing ${package_name}..."

	# path to rootfs in use
	if [[ ! -z "$DESTDIR" ]]; then
		DESTDIR="$(realpath "${DESTDIR}")"
	fi

	if [[ -d "${DESTDIR}/usr/lib/based/pkgs/${package_name}" ]]; then
		skipped_package_names+=("$package_name")
		>&2 printf '%s\n' "${package_name}: already installed"
		>&2 printf '%s\n' "${package_name}: update support not yet implemented; skipping package."
		return
	fi

	# create package directory
	mkdir -p "${DESTDIR}/usr/lib/based/pkgs/${package_name}"
	pushd "${DESTDIR}/usr/lib/based/pkgs/${package_name}" >/dev/null

	# extract package
	tar -xf "${package}"

	# check if contents/ directory exists
	if [[ -d contents ]]; then
		# check if any file conflicts
		find contents -type f -o -type l | cut -c 9- | while IFS= read -d $'\n' file; do
			if [[ -e "${DESTDIR}/$file" ]]; then
				popd >/dev/null
				rm -rf "${DESTDIR}/usr/lib/based/pkgs/${package_name}"
				>&2 printf '%s\n' "${package_name}: '${file}' already exists on host; skipping package."
				return 1
			fi
		done || { skipped_package_names+=("$package_name"); popd >/dev/null; return 0; }

		# copy contents/* to rootfs
		cp -a contents/. "${DESTDIR}/" || {
			# TODO: uninstall package
			popd >/dev/null
			rm -rf "${DESTDIR}/usr/lib/based/pkgs/${package_name}"
			skipped_package_names+=("$package_name")
			>&2 printf '%s\n' "${package_name}: failed to copy files; skipping package."
			return 0
		}

		# create package index
		find contents -type f -o -type l | cut -c 9- > contents.txt
		find contents -type d -empty | cut -c 9- >> contents.txt
		rm -rf contents
	fi

	popd >/dev/null
}

install_local_packages() {
	# function to install all local packages

	printf '%s\n' 'i: parsing package metadata...'
	for package in "$@"; do
		# check if valid metadata file
		package_metadata="$(tar -axf "${package}" --occurrence ./_pkg/manifest.yml -O)"
		if [[ ! -z "$(yq <(printf '%s' "${package_metadata}") 1>/dev/null)" ]]; then
			>&2 printf "e: invald package $(basename "${package}")"
			exit 1
		fi

		# check if package already in list
		package_name="$(yq .name <(printf '%s' "${package_metadata}"))"
		skip_package=
		for _package_name in "${package_names_to_install[@]}"; do
			if [[ "$package_name" == "${_package_name}" ]]; then
				skip_package='true'
			fi
		done
		if [[ "$skip_package" == 'true' ]]; then
			continue
		fi

		# add package to list
		packages_to_install+=("${package}")
		package_names_to_install+=("${package_name}")
	done

	# list packages being installed
	printf '%s\n' 'i: installing packages:'
	for package in "${package_names_to_install[@]}"; do
		printf '	%s\n' "$(basename "${package}")"
	done
	printf '\n'

	# prompt to proceed
	if [[ "$BASED_NONINTERACTIVE" != 'true' ]]; then
		read -p 'proceed? [y/n] ' proceed

		if [[ "${proceed,,}" != 'y' ]] && [[ "${proceed,,}" != 'yes' ]] && [[ "$proceed" != '' ]]; then
			exit
		fi
	fi
	printf '\n'

	# call install_local_package for each package
	package_index=0
	for package in "${packages_to_install[@]}"; do
		install_local_package "${package}" "${package_names_to_install[$package_index]}"
		(( package_index++ )) || true
	done
	printf '\n%s\n\n' 'installed all packages.'
}

download_packages() {
	# function to download each package

	# list packages being downloaded
	printf '%s\n' 'i: downloading packages:'
	for package in "$@"; do
		printf '	%s\n' "$package"
	done
	printf '\n'

	# prompt to proceed
	if [[ "$BASED_NONINTERACTIVE" != 'true' ]]; then
		read -p 'proceed? [y/n] ' proceed

		if [[ "${proceed,,}" != 'y' ]] && [[ "${proceed,,}" != 'yes' ]] && [[ "$proceed" != '' ]]; then
			exit
		fi
	fi
	printf '\n'

	# download each package
	for package in "$@"; do
		# TODO: download package and append to local_packages_to_install
		printf '%s\n' "downloading ${package}..."
	done
	printf '%s\n\n' 'downloaded all packages.'
}

remote_package_name() {
	# TODO: add logic to check if remote package exists
	# TODO: add support for dependency resolution

	printf '%s' "$1-1.0.0-1:some_repo"
}

resolve_packages() {
	# function to identify and distinguish between local and remote packages

	for package in "$@"; do
		if [[ -f "$package" ]]; then
			# TODO: add support for dependency resolution

			# add to local package list
			local_packages_to_install+=("$(realpath "$package")")
		elif [[ "$package" =~ ^[a-zA-Z0-9_-]+$ ]]; then
			package_to_download="$(remote_package_name "$package")"
			if [[ ! -z "$package_to_download" ]]; then
				# check if already in list
				skip_package=
				for package_name in "${package_names_to_download[@]}"; do
					if [[ "$package" == "$package_name" ]]; then
						skip_package='true'
					fi
				done
				if [[ "$skip_package" != 'true' ]]; then
					# add to remote package list
					package_names_to_download+=("$package")
					packages_to_download+=("$package_to_download")
				fi
			else
				>&2 printf '%s\n' "e: package '${package}' does not exist in any repository."
				exit 1
			fi
		else
			>&2 printf '%s\n' "e: invalid package name '${package}'"
			exit 1
		fi
	done
}

########
# main #
########

resolve_packages "${@:2}"

if (( "${#packages_to_download[@]}" > 0 )); then
	download_packages "${packages_to_download[@]}"
fi

install_local_packages "${local_packages_to_install[@]}"

run_hooks

if (( "${#skipped_package_names[@]}" > 0 )); then
	printf '%s\n' 'e: the installation of the following packages was skipped:'
	for skipped_package_name in "${skipped_package_names[@]}"; do
		printf '%s\n' "	${skipped_package_name}"
	done
	printf '\n'
fi

printf '%s\n' 'i: operation complete.'

if (( "${#skipped_package_names[@]}" > 0 )); then
	exit 1
fi
